version: '3.9'

services:
  datastore:
    image: busybox
    volumes:
      - db_data:/var/lib/mysql
      - wordpress_data:/var/www/html
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
  app:
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    restart: always
volumes:
  db_data:
  wordpress_data:
